# Generated by Django 3.2.25 on 2024-08-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheyni_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
